Style/ClassAndModuleChildren:
  Description: 'Most modules will use the non-nested syntax'
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Metrics/ClassLength:
  Description: 'Most modules are quite large. This is ok.'
  Enabled: true
  Exclude:
    - 'modules/**/*'

Style/Documentation:
  Enabled: true
  Description: 'Most Metasploit modules do not have class documentation.'
  Exclude:
    - 'modules/**/*'

Metrics/LineLength:
  Description: 'Modules often pattern match against very long strings when identifying targets.'
  Enabled: true
  Max: 180

Metrics/MethodLength:
  Enabled: true
  Description: 'While the style guide suggests 10 lines, exploit definitions often exceed 200 lines.'
  Max: 300

Style/WordArray:
  Enabled: false
  Description: 'Prefer consistent use of []'

Style/RedundantBegin:
  Exclude:
    - 'modules/**/*'

Documentation:
  Exclude:
    - 'modules/**/*'
