language: ruby
rvm:
  - 2.2.0
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - 2.2.4
  - 2.3.0
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
script: bundle exec rspec
branches:
  except:
    - gh-pages
